# Generated by Django 4.2.1 on 2023-06-05 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_category_tag_taglist_alter_recipedetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taglist',
            name='title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.recipedetail'),
        ),
        migrations.AddField(
            model_name='taglist',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='recipedetail',
            name='tags',
        ),
        migrations.AlterField(
            model_name='taglist',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='recipedetail',
            name='tags',
            field=models.CharField(default='separated by comma', max_length=100),
        ),
    ]
