# Generated by Django 4.2.1 on 2023-06-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_taglist_title_taglist_user_remove_recipedetail_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taglist',
            name='name',
        ),
        migrations.AddField(
            model_name='taglist',
            name='hash_tag',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='recipedetail',
            name='tags',
            field=models.CharField(blank=True, default='separated by comma', max_length=100),
        ),
    ]
